enable git large file storage for this repo (#182)
Our binaries are becoming bigger and bigger. In our most recent release, we encountered the following error:

```
remote: warning: File manager/Outline-Manager.dmg is 98.24 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File manager/Outline-Manager.exe is 67.71 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File manager/Outline-Manager.zip is 94.80 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: error: Trace: 6f29c64ef835aa0fe4929904c378d06ddc827dfeab49132882d85c6455867155
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File manager/Outline-Manager.AppImage is 101.86 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To https://github.com/Jigsaw-Code/outline-releases.git
 ! [remote rejected] manager/1.10.0 -> manager/1.10.0 (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/Jigsaw-Code/outline-releases.git'
```

Therefore we need to enable [Git Large File Storage (git lfs)](https://git-lfs.github.com/) for this repository.

In this PR, I did not change any binaries (they should have the same checksum), the "diff" shown here is because GitHub doesn't recognize `git lfs`. But when you [switch to this branch](https://github.com/Jigsaw-Code/outline-releases/tree/junyi/enable-git-lfs-for-binaries), you can download the correct binaries. The file sizes are:

```
----- master -----
-rwxr-xr-x   98546329 Jun 29 17:01 Outline-Client.AppImage
-rw-r--r--   71833040 Jun 29 17:01 Outline-Client.exe
-rw-r--r--   10708786 Jun 29 17:01 Outline.apk
-rw-r--r--   100853765 Jun 29 17:01 Outline-Manager.AppImage
-rw-r--r--   101702614 Jun 29 17:01 Outline-Manager.dmg
-rw-r--r--   66830000 Jun 29 17:01 Outline-Manager.exe
-rw-r--r--   98350290 Jun 29 17:01 Outline-Manager.zip

----- this branch -----
-rwxr-xr-x   98546329 Jun 29 16:48 Outline-Client.AppImage
-rw-r--r--   71833040 Jun 29 16:48 Outline-Client.exe
-rw-r--r--   10708786 Jun 29 17:00 Outline.apk
-rw-r--r--   100853765 Jun 29 16:48 Outline-Manager.AppImage
-rw-r--r--   101702614 Jun 29 16:48 Outline-Manager.dmg
-rw-r--r--   66830000 Jun 29 16:48 Outline-Manager.exe
-rw-r--r--   98350290 Jun 29 16:43 Outline-Manager.zip
```